### ISSUE TITLE
Does it run on Raspbian?

### ISSUE THREAD

**Issue by allistoncarlos** [felixrieseberg/windows95#12]
Can I use the Linux version of Raspberry Pi to run it?

**Comment by benwiley4000** [comment]
I have nothing to do with this project but I was curious so I did some research..

According to the Electron docs you can build it for ARMv7 (which I think all Raspberry Pis except for the original Model A support). https://github.com/electron/electron/blob/master/docs/tutorial/support.md#linux

So it's not released here as a binary but you should be able to build it on your Raspberry Pi if you do:

1. Install [Node.js](https://nodejs.org/en/) for your Raspberry Pi
1. `git clone https://github.com/felixrieseberg/windows95.git`
2. `npm install` (Assuming you have Node.js already installed on your Raspberry Pi)
3. `npm run make`

**Comment by ConstipatedNinja** [comment]
For nodejs on your raspi, here's the commands:

`curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -`
`sudo apt-get install -y nodejs`

You can verify by running `node -v` that nodejs is installed, and it should inform you of the version.

PSA: Since both commands that I've listed use `sudo`, please consider looking over what every part of those commands does. I'm plenty trustworthy (by virtue of not caring enough about messing with others), but there's lots of people out there who aren't as trustworthy, so it's good to get into practice of critically thinking about commands that contain `sudo` before straight-up copy-pasting them.

**Comment by allistoncarlos** [comment]
Guys, you're great! Thanks, I'll give it a try!
