### ISSUE TITLE
Can you confirm the legality of Windows 95 distribution in your product?

### ISSUE THREAD

**Issue by moskvach** [felixrieseberg/windows95#276]
⚠️ Thank you for reporting an issue!

Before we go any further, understand that I probably won't be able to fullfil feature requests.
Feel free to report what feature you'd love to see, just don't get angry when I don't have
time to implement it 🙇‍♂️

I will however _gladly_ help you make a pull request if you're willing to play with Javascript!

**Comment by moskvach** [comment]
Please confirm you are not pirating Windows 95 in your product. I'd like to see a confirmation documents.

**Comment by Sissy-Princess** [comment]
Being an "ex-Windows beta-tester" does not entitle you to "confirmation documents" about intellectual property that belongs to others.

Perhaps instead of being a busy-body on github, you could direct some of your excess energy and time to convincing your government to pull out of Ukraine and to cease committing war crimes against the Ukrainian people including rape, torture, murder, and kidnapping.

**Comment by felixrieseberg** [comment]
Hey Igor, former Microsoft Engineer here! Windows 95 is provided by WinWorldPC. Microsoft is aware of this repository, but it's provided for educational purposes only, not affiliated with Microsoft, and not endorsed.

**Comment by moskvach** [comment]
I’m sorry, I could not suppose you like Ukrainian Nazis and prefer to protect children killers.

**Comment by Sissy-Princess** [comment]
I don’t know if you’re really that deluded by Russian propaganda or you’re just terrified at what might happen to you if you don’t pretend that you are.  

https://www.pbs.org/wgbh/frontline/article/war-crimes-watch-ukraine-russia-targets-schools-bombs-future/

> I’m sorry, I could not suppose you like Ukrainian Nazis and prefer to protect children killers.
