### ISSUE TITLE
Increased Hard Drive Space!

### ISSUE THREAD

**Issue by nlogozzo** [felixrieseberg/windows95#32]
133 MB of spcae is not enough for my applications. If you don't want to increase the space of the C drive, allow the user to create another 2 GB disk image, a D drive to install their applications there

**Comment by helje5** [comment]
I'm running into the issue as well, the CD based stuff I want to try doesn't fit into the image. I tried to increase the img with `truncate`, and then use `fatresize` in a Docker image to increase that image. That kinda seems to work.
If I restart the app, the image is not there yet, but if I run `scandisk`, it starts, but eventually fails due to out of memory.

I still would love to see a way to mount another image as D:, and a bigger main partition. Well, and to get scandisk running, maybe more RAM 😬

**Comment by simonrosted** [comment]
I have a use case similar to the one helje5 describes. I have an old CD-ROM that's been made into an iso-file, with a filesize of circa 700mb, that i want to make available and mount in Windows95.

**Comment by felixrieseberg** [comment]
This is now done, I've increased the size to a full gigabyte. Thanks for the report 🙇

**Comment by helje5** [comment]
Yup, much better now, thanks a lot.

**Comment by sgibbon1** [comment]
It looks like the macOS version still only has 133 MB of available space: 
![image](https://user-images.githubusercontent.com/17695987/62745267-bd04e080-ba0f-11e9-886a-d910ac27451d.png)

**Comment by OdinEidolon** [comment]
Hello. Outstanding app!
Is there a way to increase the size of the hard drive? I'd like to install an old abandonware that has been regularly updated in unofficial ways and the game alone is almost 2 GB!
Thanks!
