### ISSUE TITLE
Publish as a snap for Linux?

### ISSUE THREAD

**Issue by dancojocaru2000** [felixrieseberg/windows95#59]
Electron apps can be quite easily be made into snaps.

Would publishing this app as a snap be an option?

[https://docs.snapcraft.io/build-snaps/electron](https://docs.snapcraft.io/build-snaps/electron)

**Comment by Mikerr1111** [comment]
I think it would be possible since Felix also made the Snap for Slack possible.

**Comment by calebo5** [comment]
yes, because electron and atom when they are used togher, windows 95 can be born

**Comment by wwderw** [comment]
I was just thinking about asking for a portable version for Linux, I'm just more of either an AppImage or a binary archive person compared to Snaps.

**Comment by malept** [comment]
> I think it would be possible since Felix also made the Snap for Slack possible.

He also wrote https://electronjs.org/docs/tutorial/snapcraft :smile:

It's not going in the Snap Store, for obvious reasons (read: legal). *If* this were to happen, I think you'd have to run `snap install --dangerous name-of-snap.snap` and that is a weird thing to be adding to the README, mostly because it opens up questions like "why is it dangerous???"

**Comment by felixrieseberg** [comment]
More than anything else, it'd increase the amount of time I'd need to publish a new version by quite a bit – and this is a toy after all. In a year, none of us will still be using this.

If we do, I might make one!

**Comment by pizzadude** [comment]
Somebody already made a snap.
