### ISSUE TITLE
Unclear compatibilty with host O/S

### ISSUE THREAD

**Issue by cheesecracker** [felixrieseberg/windows95#90]
For Windows, it's pretty sure that it won't work in XP and it should work in Win 10.  But what about in between?  Win 7 or Vista?

Is there a page on compatibility?  A little compatibility matrix would be nice.

And the same remark for other O/S, ie Mac and Linux;

**Comment by jacobq** [comment]
This application is powered by [ElectronJS](https://electronjs.org/), so I believe that it supports the same platforms as [that project does](https://electronjs.org/docs/tutorial/support#supported-platforms).
See also #51 and #95

**Comment by petrasteri** [comment]
Right.  Then please public this information somewhere on the homepage/support/whatever page

**Comment by jacobq** [comment]
The README does state [that this is an Electron app](https://github.com/felixrieseberg/windows95#windows95) and that project is [mostly a joke](https://github.com/felixrieseberg/windows95#hows-the-code). Feel free to create a PR to improve it if you don't think this is sufficiently clear, but I think you may be misunderstanding the point.

**Comment by cheesecracker** [comment]
Not being a tech savvy, I didn't know what Electron app and had no idea what that implied.  I only consider myself as a lambda user.

I did see, however, the sentence on "... a joke".  I just thought it's some kind of humour (but I didn't get the meaning) or a sign of humility :D

**Comment by cheesecracker** [comment]
I saw that someone wrote

Yes! Quite well, actually, on [platforms supported by Electron](https://electronjs.org/docs/tutorial/support#supported-platforms).

The sentence was very good.  But it was removed afterwards.  I would give a vote to keep it.

**Comment by jacobq** [comment]
@cheesecracker It seems reasonable to me that unqualified platform names like "Windows" can be assumed to refer to non-end-of-life versions (e.g. not include Windows 98, ME, XP, Vista, etc.). There's also now a link to the electron project at the top of README, which people can peruse to find those details, if they are interested.

**Comment by petrasteri** [comment]
> It seems reasonable to me that unqualified platform names like "Windows" can be assumed to refer to non-end-of-life versions (e.g. not include Windows 98, ME, XP, Vista, etc.)

Since this is a "joke" ^_^ I suppose it doesn't really matter.

For for serious matter, this kind of assumption is very dangerous.  It could ruin your relationship with your boss or your customers.

You have to know that the non-support of XP by Microsoft does NOT mean the non-functioning of XP.  If the computers are correctly protected, if people don't need new features, XP are working perfectly.  And there are still lots of XP out there.  Since we are in GitHub, do you know that Git clients can still work in XP?

For others, they might remove support of Win 7 and Win 8 altogether today to simplify programming even though they are still supported by Microsoft.

There is one sentence I learned many years ago:
**When you assume, you put an ass between you and me** :)
